apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: appuser
  MYSQL_PASSWORD: ubuntu
  DB_USER: appuser
  DB_PASSWORD: ubuntu
